# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#
# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
default_platform(:android)
platform :android do
  # desc "Runs all the tests"
  # lane :test do
  #   gradle(task: "test")
  # end
  # desc "Submit a new Beta Build to Crashlytics Beta"
  # lane :beta do
  #   gradle(task: "clean assembleRelease")
  #   crashlytics
  #   # sh "your_script.sh"
  #   # You can also use other beta testing services here
  # end
  desc "build-apk"
  lane :build_apk do
      gradle(task: "assembleRelease", project_dir: "./android")
  end
  desc "build-bundle"
  lane :build_bundle do
      gradle(task: "bundleRelease", project_dir: "./android")
  end
  desc "build-bundle-and-upload"
  lane :build_and_upload do
    # Build the AAB
    gradle(task: "bundleRelease", project_dir: "./android")
    # Upload the AAB to Google Play
    supply(
      aab: "./android/app/build/outputs/bundle/release/app-release.aab", # Path to AAB
      track: "internal"
    )
  end
end